<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="app.psc.testcases.accountverification.accountverificationtest_plan" tests="2" time="21.004" ignored="3" failures="0" timestamp="24 May 2017 11:22:09 GMT" skipped="0" hostname="XWJPMDD035" errors="2">
  <testcase name="TC012_02_Verify_User_Access_New_Plan_For_Valid_Input" time="10.367" classname="app.psc.testcases.accountverification.accountverificationtest_plan">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
]]>
    </error>
  </testcase> <!-- TC012_02_Verify_User_Access_New_Plan_For_Valid_Input -->
  <testcase name="TC012_01_Verify_User_Access_New_Plan_For_Invalid_Input" time="10.637" classname="app.psc.testcases.accountverification.accountverificationtest_plan">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at app.psc.testcases.accountverification.accountverificationtest_plan.TC012_01_Verify_User_Access_New_Plan_For_Invalid_Input(accountverificationtest_plan.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- TC012_01_Verify_User_Access_New_Plan_For_Invalid_Input -->
  <testcase name="TC010_01_Verify_Restyled_Button_Home_Page_For_Sentence_Case" classname="app.psc.testcases.login.logintestcases">
    <skipped/>
  </testcase> <!-- TC010_01_Verify_Restyled_Button_Home_Page_For_Sentence_Case -->
  <testcase name="TC008_01_Verify_Equality_Of_SessionID_From_Browser_And_DB" classname="app.psc.testcases.login.logintestcases">
    <skipped/>
  </testcase> <!-- TC008_01_Verify_Equality_Of_SessionID_From_Browser_And_DB -->
  <testcase name="TC009_01_Verify_To_Do_List_Site_Navigator" classname="app.psc.testcases.login.logintestcases">
    <skipped/>
  </testcase> <!-- TC009_01_Verify_To_Do_List_Site_Navigator -->
</testsuite> <!-- app.psc.testcases.accountverification.accountverificationtest_plan -->
